[package]
name = "xml-mut-xot"
version = "0.1.0"
authors = ["Tomas Dambrauskas <tomas.sql@proton.me>"]
edition = "2021"

[dependencies]
xot = { git = "https://github.com/tomuxmon/xot" }
xml-mut-data = { path = "../xml-mut-data" }
